import { OrgGraph } from "./components/OrgGraph";
import nodesData from "./data/nodes.json";
import type { PersonNode, HierarchyEdge } from "./types";

const nodes: PersonNode[] = nodesData;

// Sample hierarchy for testing - all initial edges are auto-generated
const edges: HierarchyEdge[] = [
  { from: "1", to: "2", isAutoGenerated: true },
  { from: "1", to: "3", isAutoGenerated: true },
  { from: "2", to: "4", isAutoGenerated: true },
  { from: "2", to: "5", isAutoGenerated: true },
  { from: "3", to: "6", isAutoGenerated: true },
  { from: "3", to: "7", isAutoGenerated: true },
];

function App() {
  return (
    <div style={{ width: "100vw", height: "100vh", overflow: "hidden" }}>
      <OrgGraph nodes={nodes} edges={edges} />
    </div>
  );
}

export default App;
