export interface PersonNode {
  id: string;
  label: string;
}

export interface HierarchyEdge {
  from: string;
  to: string;
  isAutoGenerated?: boolean;
}

export interface NodeMetadata {
  role?: string;
}

export interface VisNode {
  id: string;
  name: string; // Original person name
  label: string; // Formatted display label (may include role)
  metadata?: NodeMetadata;
  x?: number;
  y?: number;
  isRoot?: boolean;
  color?: { background: string; border: string }; // For highlighting
}

/**
 * Formats a node's display label from its name and metadata.
 */
export function formatNodeLabel(name: string, metadata?: NodeMetadata): string {
  if (!metadata?.role) return name;
  return `<b>${metadata.role}</b>\n${name}`;
}

/**
 * Creates a node update object, preserving essential fields (name, label, metadata).
 * Use this when updating nodes to avoid accidentally losing data.
 */
export function updateNode(node: VisNode, changes: Partial<VisNode>): VisNode {
  return {
    id: node.id,
    name: node.name,
    label: node.label,
    metadata: node.metadata,
    ...changes,
  };
}

export interface VisEdge {
  id: string;
  from: string;
  to: string;
  dashes?: boolean;
  title?: string;
}

/**
 * Output node data for onChange callback.
 * Contains the essential data consumers need to persist.
 */
export interface OutputNode {
  id: string;
  name: string;
  metadata?: NodeMetadata;
  isRoot?: boolean;
}

/**
 * Output edge data for onChange callback.
 */
export interface OutputEdge {
  from: string;
  to: string;
}

/**
 * Data passed to the onChange callback when the graph state changes.
 */
export interface GraphChangeData {
  nodes: OutputNode[];
  edges: OutputEdge[];
}

/**
 * Represents a subtree: a node and all its descendants with their relative positions.
 * This is the core abstraction for moving nodes with their children.
 */
export interface SubtreeContext {
  rootId: string;
  descendantIds: string[];
  relativePositions: Record<string, { dx: number; dy: number }>;
}

export interface DragState {
  originalX: number;
  originalY: number;
  snappedOut: boolean;
  highlightedNodeId: string | null;
  isOverTopBar: boolean;
  subtree: SubtreeContext;
  /** Offset between click point and node center (calculated on first drag event) */
  pointerOffset: { dx: number; dy: number } | null;
}

// =============================================================================
// Graph Accessor API (for inspecting current graph state)
// =============================================================================

/**
 * Position in DOM coordinates (pixels relative to viewport).
 */
export interface Position {
  x: number;
  y: number;
}

/**
 * Node state info returned by GraphAccessor.
 * Includes current DOM position for building overlays or integrations.
 */
export interface NodeStateInfo {
  id: string;
  label: string;
  isRoot: boolean;
  position: Position;
}

/**
 * Edge state info returned by GraphAccessor.
 */
export interface EdgeStateInfo {
  id: string;
  from: string;
  to: string;
  dashes: boolean;
}

/**
 * Accessor for querying the current graph state.
 * Useful for building overlays, integrations, or inspecting the graph.
 */
export interface GraphAccessor {
  /** Get all nodes with their current DOM positions. */
  getNodes(): NodeStateInfo[];
  /** Get all edges with their connection info. */
  getEdges(): EdgeStateInfo[];
}
