export interface PersonNode {
  id: string;
  label: string;
}

export interface HierarchyEdge {
  from: string;
  to: string;
  isAutoGenerated?: boolean;
}

export interface NodeMetadata {
  role?: string;
}

export interface VisNode {
  id: string;
  name: string; // Original person name
  label: string; // Formatted display label (may include role)
  metadata?: NodeMetadata;
  x?: number;
  y?: number;
  isRoot?: boolean;
}

/**
 * Formats a node's display label from its name and metadata.
 */
export function formatNodeLabel(name: string, metadata?: NodeMetadata): string {
  if (!metadata?.role) return name;
  return `<b>${metadata.role}</b>\n${name}`;
}

export interface VisEdge {
  id: string;
  from: string;
  to: string;
  dashes?: boolean;
  title?: string;
}

/**
 * Represents a subtree: a node and all its descendants with their relative positions.
 * This is the core abstraction for moving nodes with their children.
 */
export interface SubtreeContext {
  rootId: string;
  descendantIds: string[];
  relativePositions: Record<string, { dx: number; dy: number }>;
}

export interface DragState {
  originalX: number;
  originalY: number;
  snappedOut: boolean;
  highlightedNodeId: string | null;
  isOverTopBar: boolean;
  subtree: SubtreeContext;
  /** Offset between click point and node center (calculated on first drag event) */
  pointerOffset: { dx: number; dy: number } | null;
}
